# Site settings
title: "The Atomic Human"
description: "Exploring the themes, reflections, and ideas from Neil D. Lawrence's book 'The Atomic Human'."
baseurl: "" # Leave blank for root or update if deploying to a subdirectory
url: "https://the-atomic-human.ai" # Update with your Netlify site URL

# Author information
author:
  name: "Neil D. Lawrence"

# Collections configuration for Jekyll
collections:
  archive:
    output: true
    permalink: /archive/:title/
  chapters:
    output: true
    permalink: /chapters/:title/
  themes:
    output: true
    permalink: /themes/:title/
  reviews:
    output: true
    permalink: /reviews/:title/
  machine_reviews:
    output: true
    permalink: /machine_reviews/:title/
  people:
    output: true
    permalink: /people/:name/
  bibliography:
    output: true
    permalink: /bibliography/:title/
  reflections:
    output: true
    permalink: /reflections/:title/
  history:
    output: true
    permalink: /history/:title/
  technology:
    output: true
    permalink: /technology/:title/
  images:
    output: true
    permalink: /images/:title/

# Default front matter for collections
defaults:
  - scope:
      path: "_archive"
    values:
      layout: archive
  - scope:
      path: "_chapters"
    values:
      layout: chapter
  - scope:
      path: "_themes"
    values:
      layout: theme
  - scope:
      path: "_reviews"
    values:
      layout: review
  - scope:
      path: "_machine_reviews"
    values:
      layout: machine_review
  - scope:
      path: "_people"
    values:
      layout: person
  - scope:
      path: "_bibliography"
    values:
      layout: bibliography
  - scope:
      path: "_reflections"
    values:
      layout: reflection
  - scope:
      path: "_history"
    values:
      layout: history
      event: "deault-event"
  - scope:
      path: "_technology"
    values:
      layout: technology
  - scope:
      path: "_images"
    values:
      layout: image

# For giti settings
ghub:
  edit: true
  repository: atomichuman.github.io
github_username: atomichuman
      
# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: atomichuman/atomic-human-theme@main
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalinks
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Pagination (if needed)
paginate: 5
paginate_path: "/page:num/"

# Metadata
metadata:
  isbn: "978-0-241-62524-8"
  publisher: "Allen Lane"
  publication_year: 2024
  tagline: "Understanding Ourselves in the Age of AI"

# Social links
social_links:
  twitter: "https://twitter.com/lawrennd"
  github: "https://github.com/atomic-human"
  linkedin: "https://www.linkedin.com/in/neil-lawrence-129a22127"

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed
