backend:
  name: github
  repo: atomichuman/atomichuman.github.io # Path to your GitHub repository
  # optional, defaults to master
  branch: main


media_folder: "assets/images"  # Where uploaded files will be stored
public_folder: "/assets/images"  # Public folder path

collections:
  - name: "reviews"
    label: "Reviews"
    folder: "_reviews"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["podcast", "print", "television"] }
      - { label: "Publication", name: "publication", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Extract", name: "extract", widget: "text" }
      - { label: "Comment", name: "comment", widget: "text" }
      - label: "Contributed By"
        name: "contributed_by"
        widget: "object"
        fields:
          - label: "Initial Contribution"
            name: "initial"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["human", "machine"] }
              - { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id", required: false }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Tool", name: "tool", widget: "string", required: false }
              - { label: "Version", name: "version", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Notes", name: "notes", widget: "text", required: false }
          - label: "Reviewed By"
            name: "reviewed_by"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["human", "machine"] }
              - { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id", required: false }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Tool", name: "tool", widget: "string", required: false }
              - { label: "Version", name: "version", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Notes", name: "notes", widget: "text", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "reflections"
    label: "Reflections"
    folder: "_reflections"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - label: "Contributed By"
        name: "contributed_by"
        widget: "object"
        fields:
          - label: "Initial Contribution"
            name: "initial"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["human", "machine"] }
              - { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id", required: false }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Tool", name: "tool", widget: "string", required: false }
              - { label: "Version", name: "version", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Notes", name: "notes", widget: "text", required: false }
          - label: "Reviewed By"
            name: "reviewed_by"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["human", "machine"] }
              - { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id", required: false }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Tool", name: "tool", widget: "string", required: false }
              - { label: "Version", name: "version", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Notes", name: "notes", widget: "text", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "chapters"
    label: "Chapters"
    folder: "_chapters"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Chapter Number", name: "number", widget: "number" }
      - label: "Contributed By"
        name: "contributed_by"
        widget: "object"
        fields:
          - label: "Initial Contribution"
            name: "initial"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["human", "machine"] }
              - { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id", required: false }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Tool", name: "tool", widget: "string", required: false }
              - { label: "Version", name: "version", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Notes", name: "notes", widget: "text", required: false }
          - label: "Reviewed By"
            name: "reviewed_by"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["human", "machine"] }
              - { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id", required: false }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Tool", name: "tool", widget: "string", required: false }
              - { label: "Version", name: "version", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Notes", name: "notes", widget: "text", required: false }
      - { label: "Themes", name: "themes", widget: "relation", collection: "themes", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Historical Events", name: "historical_events", widget: "relation", collection: "history", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Images", name: "images", widget: "relation", collection: "images", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Bibliography", name: "bibliography", widget: "relation", collection: "bibliography", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Technology", name: "technology", widget: "relation", collection: "technology", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Content", name: "body", widget: "markdown" }
