backend:
  name: github
  repo: atomichuman/atomichuman.github.io # Path to your GitHub repository
  # optional, defaults to master
  branch: main


media_folder: "assets/images"  # Where uploaded files will be stored
public_folder: "/assets/images"  # Public folder path

collections:
  - name: "reviews"
    label: "Reviews"
    folder: "_reviews"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["podcast", "print", "television"] }
      - { label: "Publication", name: "publication", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Extract", name: "extract", widget: "text" }
      - { label: "Comment", name: "comment", widget: "text" }
      - { label: "Contributed By", name: "contributed_by", widget: "object", fields: [
          { label: "Type", name: "type", widget: "select", options: ["human", "machine"] },
          { label: "Name", name: "name", widget: "string" },
          { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id" },
          { label: "Date", name: "date", widget: "date" },
          { label: "Notes", name: "notes", widget: "text" }
        ] }

  - name: "reflections"
    label: "Reflections"
    folder: "_reflections"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Contributed By", name: "contributed_by", widget: "object", fields: [
          { label: "Type", name: "type", widget: "select", options: ["human", "machine"] },
          { label: "Name", name: "name", widget: "string" },
          { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id" },
          { label: "Date", name: "date", widget: "date" },
          { label: "Notes", name: "notes", widget: "text" }
        ] }
      - { label: "Featured Image", name: "featured_image", widget: "image" }

  - name: "chapters"
    label: "Chapters"
    folder: "_chapters"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Chapter Number", name: "number", widget: "number" }
      - { label: "Contributed By", name: "contributed_by", widget: "object", fields: [
          { label: "Type", name: "type", widget: "select", options: ["human", "machine"] },
          { label: "Name", name: "name", widget: "string" },
          { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id" },
          { label: "Date", name: "date", widget: "date" },
          { label: "Notes", name: "notes", widget: "text" }
        ] }
      - { label: "Themes", name: "themes", widget: "relation", collection: "themes", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Historical Events", name: "historical_events", widget: "relation", collection: "history", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Images", name: "images", widget: "relation", collection: "images", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Bibliography", name: "bibliography", widget: "relation", collection: "bibliography", search_fields: ["title"], value_field: "title", multiple: true }
      - { label: "Technology", name: "technology", widget: "relation", collection: "technology", search_fields: ["title"], value_field: "title", multiple: true }

  - name: "themes"
    label: "Themes"
    folder: "_themes"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Contributed By", name: "contributed_by", widget: "object", fields: [
          { label: "Type", name: "type", widget: "select", options: ["human", "machine"] },
          { label: "Name", name: "name", widget: "string" },
          { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id" },
          { label: "Date", name: "date", widget: "date" },
          { label: "Notes", name: "notes", widget: "text" }
        ] }

  - name: "technology"
    label: "Technology"
    folder: "_technology"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Period", name: "period", widget: "string" }
      - { label: "Contributed By", name: "contributed_by", widget: "object", fields: [
          { label: "Type", name: "type", widget: "select", options: ["human", "machine"] },
          { label: "Name", name: "name", widget: "string" },
          { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id" },
          { label: "Date", name: "date", widget: "date" },
          { label: "Notes", name: "notes", widget: "text" }
        ] }

  - name: "history"
    label: "History"
    folder: "_history"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Period", name: "period", widget: "string" }
      - { label: "Contributed By", name: "contributed_by", widget: "object", fields: [
          { label: "Type", name: "type", widget: "select", options: ["human", "machine"] },
          { label: "Name", name: "name", widget: "string" },
          { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id" },
          { label: "Date", name: "date", widget: "date" },
          { label: "Notes", name: "notes", widget: "text" }
        ] }

  - name: "bibliography"
    label: "Bibliography"
    folder: "_bibliography"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Author", name: "author", widget: "list", fields: [
          { label: "Given", name: "given", widget: "string" },
          { label: "Family", name: "family", widget: "string" },
          { label: "Prefix", name: "prefix", widget: "string" },
          { label: "Suffix", name: "suffix", widget: "string" }
        ] }
      - { label: "ISBN", name: "isbn", widget: "string" }
      - { label: "Publisher", name: "publisher", widget: "string" }
      - { label: "Edition", name: "edition", widget: "string" }
      - { label: "Contributed By", name: "contributed_by", widget: "object", fields: [
          { label: "Type", name: "type", widget: "select", options: ["human", "machine"] },
          { label: "Name", name: "name", widget: "string" },
          { label: "Person ID", name: "person_id", widget: "relation", collection: "people", search_fields: ["title"], value_field: "person_id" },
          { label:
